In [1]:
import numpy as np

In [9]:
arr3d = np.arange(50).reshape(5,5,2)
arr3d

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]],

       [[20, 21],
        [22, 23],
        [24, 25],
        [26, 27],
        [28, 29]],

       [[30, 31],
        [32, 33],
        [34, 35],
        [36, 37],
        [38, 39]],

       [[40, 41],
        [42, 43],
        [44, 45],
        [46, 47],
        [48, 49]]])

In [15]:
# Lấy từ row[0] đến hết, trong mỗi row lấy 2 dòng
arr3d[0:,:2]

array([[[ 0,  1],
        [ 2,  3]],

       [[10, 11],
        [12, 13]],

       [[20, 21],
        [22, 23]],

       [[30, 31],
        [32, 33]],

       [[40, 41],
        [42, 43]]])

In [10]:
arr_3d = np.arange(50).reshape(5,2,5)
arr_3d

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29]],

       [[30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]])