In [2]:
import numpy as np

In [3]:
arr_index = np.arange(0,11)
arr_index

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr_index[8:9]

array([8])

In [6]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
#arr_2d

In [7]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [8]:
arr_2d[:2][:]

array([[ 5, 10, 15],
       [20, 25, 30]])